# Generated by Django 4.1.4 on 2022-12-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="snippet",
            name="code",
            field=models.TextField(blank=True),
        ),
    ]
